### ISSUE TITLE
mysqldump: unrecognized option `--single-transaction`

### ISSUE THREAD

**Issue by pdewouters** [humanmade/hm-backup#40]
````
mysqldump: unrecognized option --single-transaction
````
mysqldump Ver 8.22 Distrib 3.23.52, for suse-linux (i686)`

I had a couple of questions about this single transaction business. Any idea if it's something we can fix?

http://wordpress.org/support/topic/plugin-backupwordpress-backup-fails-with-mysqldump-unrecognized-option?replies=3#post-4587313

**Comment by willmot** [comment]
This issue was moved to humanmade/backupwordpress#708
