### ISSUE TITLE
mysqldump causing fatal error on crashed tables

### ISSUE THREAD

**Issue by pdewouters** [humanmade/hm-backup#41]
<pre>mysqldump: Couldn\'t execute \'show create table `wp_TABLE_STATISTICS`\': Table \'./db85564_7/wp_TABLE_STATISTICS\' is marked as crashed and should be repaired (145)
Undefined variable: rows_cnt, /kunden/85564_60598/webseiten/wp/_wp/wp-content/plugins/backupwordpress/hm-backup/hm-backup.php, 1488

Undefined variable: fields_cnt, /kunden/85564_60598/webseiten/wp/_wp/wp-content/plugins/backupwordpress/hm-backup/hm-backup.php, 1492

mysql_fetch_row(): supplied argument is not a valid MySQL result resource, /kunden/85564_60598/webseiten/wp/_wp/wp-content/plugins/backupwordpress/hm-backup/hm-backup.php, 1512

mysql_free_result(): supplied argument is not a valid MySQL result resource, /kunden/85564_60598/webseiten/wp/_wp/wp-content/plugins/backupwordpress/hm-backup/hm-backup.php, 1553HMBKP_SUCCESS</pre>

**Comment by willmot** [comment]
This issue was moved to humanmade/backupwordpress#707
