### ISSUE TITLE
Check mysql user actually has access to the database via mysqldump

### ISSUE THREAD

**Issue by willmot** [humanmade/hm-backup#57]
Sometimes the mysql user specified in `wp-config.php` might not actually have access to the database via `mysqldump`.

````
mysqldump: Got error: 1045: Access denied for user \'jci_jciuser\'@\'localhost\' (using password: YES) when trying to connect
````

**Comment by owaincuvelier** [comment]
I have currently 1 outstanding ticket from a user with this problem. Just thought I'd let you know.

**Comment by willmot** [comment]
👍

**Comment by willmot** [comment]
This issue was moved to humanmade/backupwordpress#698
